version: "3.9"
services:
  rtmp:
    build: ./rtmp
    ports:
      - "1935:1935"
      - "9200:9200"
    volumes:
      - ./data/mnt:/mnt/
      - ./data/log:/var/log/nginx/
    container_name: mixyboos_rtmp
    extra_hosts:
      - "dev.podnoms.com:10.1.1.1"
