version: "3.9"
services:
  rtmp:
    build: ./rtmp
    ports:
      - "1935:1935"
      - "8080:8080"
    volumes:
      - ./data:/tmp/hls
    container_name: mixyboos_rtmp
    extra_hosts:
    - "dev.podnoms.com:10.1.1.1"