worker_processes auto;
rtmp_auto_push on;
events {}
rtmp {
    server {
        listen 1935;
        listen [::]:1935 ipv6only=on;

        application live {
            live on;
            hls on;
            hls_path /tmp/hls;
            hls_fragment 10s;
            hls_playlist_length 5m;

            record off;
            on_publish http://localhost:8080/validate_key;
        }
    }
}

http {
    server {
        listen 8080;
        location / {
            root /www;
        }

        location /validate_key {
            proxy_pass https://dev.podnoms.com:3000/api/auth/stream;
            proxy_ssl_verify off;
        }

        location /hls {
            types {
                application/vnd.apple.mpegurl m3u8;
                application/octet-stream ts;    
            }
            root /tmp;
            add_header Cache-Control no-cache;
            add_header Access-Control-Allow-Origin *;
        }
    }
}